### ISSUE TITLE
Infos about

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [terrafx/terrafx#1]
more infos about the project we'll be good to help for contribution :)

**Comment by tannergooding** [comment]
Currently still a work in progress, but some of the core documentation files for the repo now exist.

**Comment by JeanPhilippeKernel** [comment]
Great so I'll go read it :) ,

**Comment by tannergooding** [comment]
Going to close this now. I've added a number of docs decsribing design, contributing, building, showcasing samples, etc.
