### ISSUE TITLE
HelloCombined

### ISSUE THREAD

**Issue by IngmarBitter** [terrafx/terrafx#116]
#### Description (optional)

**HelloCombined** is a sample that combines multiple of the single feature samples. At a minimum those of **HelloTexture** and **HelloConstBuffer**. The point is to show how to set the shaders and pipeline state such that all combined features are considered simultaneously.

#### Rationale

This sample is useful since it steps up implementation complexity a little. So it shows the next step toward a little more realistic application use.

#### Proposed API

Same as the other **Hello*** samples, derived from **HelloWindow**

#### Other thoughts

The class name initially would be more matchingly HelloTextureConstBuffer, but if more basic features are added then we do not want to have to change the class name. So HelloCombined is a little more future proof.

**Comment by tannergooding** [comment]
Closing as this was completed and merged with https://github.com/terrafx/terrafx/pull/117
