### ISSUE TITLE
Ambiguities 

### ISSUE THREAD

**Issue by juliusfriedman** [terrafx/terrafx#159]
https://github.com/terrafx/terrafx/blob/1ced4b14d2c4b77b911d0b872ea736bb1f4f7b2a/sources/Core/Numerics/Vector2.cs#L17

Amongst other places you define an ABI and API for a Vectoral type.

You constantiate the  static symbol UnitX and UnitY as a version of a two values which therein are constant components representing the Unit of X or Y for ALL vector types instated of such.

This should be DefaultUnitX and DefaultUnitY and really should NOT be defined in the ordinate space of what you are defining as it becomes concrete and not discrete.

Given the arbitrary sequence [1,0,1,1]  and staring at position [1] the only 0 value present that would appear as a UnitY where as the underlying unit is actually UnitX.

Furthermore the Unit is not a specific component of the vector and is discrete amongst the components and MUST not be mistaken for such.

The vector whose components do not reside in the realm of the ordinates and is defined as just for the purpose of orientation and always exists is a must better sentinel value IMHO.

Regards.

**Comment by tannergooding** [comment]
A unit vector is simply a vector whose length is 1. `UnitX`, `UnitY`, `UnitZ`, and `UnitW` are merely the standard unit vectors for each component and are represented as `X̂`, `Ŷ`, `Ẑ`, and `Ŵ`, respectively.

These values, particularly with regards to their use in multimedia, are useful for masking, scaling, and various other operations as they define the standard basis for the vector.

**Comment by tannergooding** [comment]
See also https://mathworld.wolfram.com/UnitVector.html and https://mathworld.wolfram.com/StandardBasis.html for the general mathematical definition that these were named for.

**Comment by juliusfriedman** [comment]
Without a strong concept of cardinality I feel the design where identity of the unit being the vector of in itself is not good for posterity.

Thanks for the links.

**Comment by tannergooding** [comment]
I'm not sure I understand what you're saying here. Could you, perhaps with some pseudo-code, give an example of where or how you think this will be confusing to consumers of the API?

These are static members of the types and on the types with a given number of dimensions.

`Vector2.UnitX` is therefore a unit vector with 2 dimensions where `X` is `1` and `Y` is `0`.
`Vector3.UnitY` is therefore a unit vector with 3 dimensions where `X` is `0`, `Y` is `1`, and `Z` is zero.

I would assume this means there is no ambiguity about the number of dimensions, about it applying to an instance vs being a common value of the type (it is static), nor about what it means if you are somewhat familiar with vectors, other multimedia oriented vector math libraries, or with the Vector2/3/4 types exposed by the .NET Libraries.

**Comment by juliusfriedman** [comment]
Will do my best when I have time, thank you for the interest.

**Comment by tannergooding** [comment]
> What I can say immediately given your example is that its poorly coupled because its relative to where the observation happens, e.g. if I start observing the vector from an ABI where unaligned access occurs or I otherwise have a off by 1 error the unit changes based on my initial reading where as if decoupled it would not. If the static symbol changes then I also change my unit for ALL vectors

This sounds like an issue in how elements are accessed (or I am misunderstanding). No matter how you load a vector, whether aligned, unaligned, etc; the first component is always X, the second is always Y, etc. Having an off by one error in the logic that loads a vector doesn't change how the components of the struct are ordered nor that UnitX is a vector where `X` is `1` and all other elements are `0`.

**Comment by juliusfriedman** [comment]
Quite simply, What about if my vector is retarted of you vector?

Would I not need a sentinel or field vector to reconcile the two?

Byte order also comes into question in various phases;  since your definition is rooted in of itself it creates many such problems which are therefor inherited implementation baggage.

**Comment by juliusfriedman** [comment]
I offer this in rebuttal:

```
/// <summary>
    /// Represents the 4 bytes which describe an intergal value.
    /// Each bit in the integreal can also represent a discrete attribute such that combinations produce unique values.
    /// For example `<see cref="Axis.X"/>|<see cref="Axis.Y"/> === 3`,
    /// HasFlag(<see cref="Axis.X"/>) is <see langword="true"/>,
    /// HasFlag(<see cref="Axis.Y"/>) is also <see langword="true"/> then.
    /// </summary>
    [System.Flags]
    public enum Axis : int
    {
        MinValue = int.MinValue,
        Dontcare = NetTopologySuite.Geometries.Dimension.Dontcare,
        None = 0,
        X = 1, //TODO use binary literal
        Horizontal = X,
        Longitudinal = Horizontal,
        Roll = Horizontal,
        Y = 2,//TODO use binary literal
        Vertical = Y,
        Lateral = Vertical,
        Transverse = Lateral,
        Pitch = Transverse,        
        Z = 4, //TODO use binary literal    
        Azimuth = Z,
        Depth = Azimuth,
        Yaw = Depth,
        Heading = Yaw,
        Inverse = Depth,
        W = 8,//TODO use binary literal        
        A = 16,//TODO use binary literal      
        B = 32,//TODO use binary literal        
        C = 64,//TODO use binary literal
        D = 128,//TODO use binary literal
        Spherical = 9,//TODO use binary literal
        Cylindrical = 15,//TODO use binary literal
        Hyperbolic = 31,//TODO use binary literal
        Quantized = Hyperbolic,
        MaxValue = int.MaxValue
    }
```

**Comment by tannergooding** [comment]
> What about if my vector is retarted of your vector?

Not sure what you mean here. If this is the word I think it is, I'd suggested picking a different one: https://github.com/terrafx/terrafx/blob/main/docs/CODE_OF_CONDUCT.md
If you are trying to say your vector is less advanced or a subset of; then that is functionally what `Vector2` is to `Vector3`, the additional dimension is generally assumed to be `0` in these cases or explicitly provided on upcast.

> Byte order also comes into question in various phases; since your definition is rooted in of itself it creates many such problems which are therefor inherited implementation deficiency.

Byte order doesn't matter. A `Vector4` is defined as `4x float` fields, a `float` is a primitive and is always loaded by the underlying platform in the host endianness. If, for some reason, the endianness differs from the host or you are dealing with raw bytes, then you need to know the source endianness and use the relevant `System.Buffers..Binary.BinaryPrimitives` methods (such as `ReadInt32LittleEndian` or `ReadInt32BigEndian`) to ensure it is read using the source endianness and converted to the host endianness (which may be a nop).

These types are not meant to be general purpose vector types that work in any theoretical space. If they were, they would be highly inefficient.
Instead, they are considered standard Euclidean vector types in 2, 3, or 4 dimensional space. You can suitably use these with the relevant methods to represent typical Cartesian coordinates or more advanced concepts like spherical coordinates, although the latter typically requires explicit methods which document that is how the inputs are interpreted.

This is how the majority of multimedia oriented vector math libraries functions. This includes things like Unity, DirectX Math (DXMath), OpenGL Math (GLM), etc.

**Comment by juliusfriedman** [comment]
Not sure of what word your referring to, here is a link for you https://en.wikipedia.org/wiki/Retarded_time

Byte order does matter specialy on proc which change it.

Highly inefficient to read an int /nit or float tsk tsk I think not. I think your vector type would be inefficient compared to such but I digress

You don't have to document something which is the ABI ... your running on it. the framework encapsulated it...

Its not the layout its how you defined it, X is X not 0,1, if I happen to arbitrarily have the abi representation of 0,1 that is not UnitX nor UnitY its the set {0,1}.

**Comment by tannergooding** [comment]
> Byte order does matter specialy on proc which change it.

Byte order does not typically matter because most code isn't dealing with raw bytes. Most code is dealing with concrete types defined in C# and where everything is type safe. When you are dealing with raw bytes or reinterpreting bytes via unsafe, there are helper functions on `System.Buffers.Binary.BinaryPrimitives` to help ensure they are converted appropriately.

> Highly inefficient to read an int /nit or float tsk tsk I think not. I think your vector type would be inefficient compared to such but I digress

These types, in particular, will be hardware accelerated using the available SIMD instructions. Having to check an enum to determine how the fields should be handled would indeed slow down the code overall.
They are explicitly Euclidean vectors in Euclidean space. Therefore, they are most accurately representative of Cartesian coordinates, but could also be used as spherical coordinates for a function that explicitly documented itself to handle them as such.
This, ultimately, allows a single struct to be useable for all the required scenarios and without needing to explicitly track which system they are representative of. Instead, that knowledge is "implicit" based on which function consumes them or which type exposes them.

> Its not the layout its how you defined it, X is X not 0,1, if I happen to arbitrarily have the abi representation of 0,1 that is not UnitX nor UnitY its the set {0,1}.

You are certainly free to treat the values however you want. But the API will always expose itself as a set of Cartesian coordinates and therefore `X` is always the first element, `Y` is always the second, `Z` is always the third, etc.
Therefore `UnitX` is strictly defined as `(1, 0, 0)`. This is standard in all multimedia based applications and I have not seen any evidence that this is undesirable nor that it has been harmful to the plethora of other Vector Mathematics libraries that exist.
