### ISSUE TITLE
D3D12.HelloTexture throw Out of memory

### ISSUE THREAD

**Issue by lindexi** [terrafx/terrafx#208]
#### Description (optional)

```
TerraFX.Samples.exe D3D12.HelloTexture
Running: D3D12.HelloTexture
Out of memory.
```

#### Reproduction Steps

I build and run the the TerraFX.Samples.

#### Expected Behavior

It can work well.

#### Actual Behavior

The window is hangs and the console outputs out of memory.

**Comment by tannergooding** [comment]
This was due to the memory allocator not supporting UMA based devices yet.

**Comment by lindexi** [comment]
Thank you @tannergooding
