### ISSUE TITLE
[PROPOSAL] Make IAudioAdapter read-only

### ISSUE THREAD

**Issue by FiniteReality** [terrafx/terrafx#46]
# Description (optional)

From #26, we agreed that:

> It seems wrong that users can modify the name, description, sample rate of the adapter; but doing so does nothing

As such, I believe we should make it read-only to prevent these cases, and add a separate class to handle the case which required these to be mutable.

# Rationale

By adding a separate class to contain a "request" to find the closest matching adapter, we can simplify our code and make it less confusing to users.

# Proposed API

```diff
 public interface IAudioAdapter
 {
     /// <summary>The type of device this adapter represents.</summary>
-    AudioDeviceType DeviceType { get; set; }
+    AudioDeviceType DeviceType { get; }
 
     /// <summary>The name of the adapter.</summary>
-    string Name { get; set; }
+    string Name { get; }
 
     /// <summary>The sample rate the adapter operates at.</summary>
-    int SampleRate { get; set; }
+    int SampleRate { get; }
 
     /// <summary>The number of bits in each sample this adapter operates at.</summary>
-    int BitDepth { get; set; }
+    int BitDepth { get; }
 
     /// <summary>The number of channels this adapter operates at.</summary>
-    int Channels { get; set; }
+    int Channels { get; }
 
     /// <summary>The endianness of the adapter.</summary>
     /// <remarks>If the adapter operates in big endian mode (MSB first), this will be <c>true</c>; otherwise, it operates in little endian mode (LSB first) and will be <c>false</c>.</remarks>
-    bool IsBigEndian { get; set; }
+    bool IsBigEndian { get; }
 }
 
 // Documentation is roughly the same as IAudioAdapter, except it talks about filtering instead of the adapter.
 // Abstract as implementations will likely have more properties to filter on.
+public abstract class AudioAdapterFilter
+{
+    AudioDeviceType? DeviceType { get; set; }
+    string? Name { get; set; }
+    int? SampleRate { get; set; }
+    int? BitDepth { get; set; }
+    int? Channels { get; set; }
+    bool? IsBigEndian { get; set; }
+}
 
 public interface IAudioProvider
 {
     // Searches for the adapter with the closest properties
+    ValueTask<IAudioAdapter> GetClosestAdapterAsync(AudioAdapterFilter filter);
 }
```

# Drawbacks

There is no way of identifying how "close" the user wants the returned adapter to be. They could be fine with a varying sample rate or bit depth, for example. We should add documentation on how to correctly request a device so that the user can handle the inevitable case where these properties do not match up.

# Alternatives

None yet.

# Other thoughts

~~We could possibly just throw NotSupportedException on set instead of making a separate type, and then keep the interface as is, to allow passing an existing set of properties through, but this might just confuse users further.~~ Solved by making RequestAudio(Playback/Recording)Device take an IAudioAdapter, and exposing a "find closest device" method.

# Discussions

https://github.com/terrafx/terrafx/pull/26#pullrequestreview-296616592
https://github.com/terrafx/terrafx/pull/26#pullrequestreview-296620598
that have been made thus far.

**Comment by tannergooding** [comment]
> There is no way of identifying how "close" the user wants the returned adapter to be.

Maybe, instead of returning the "closest" and taking a "filter" we could expose a function that takes a "predicate" that is called for each "device descriptor" that allows them to decide if it "fits" without actually instantiating something on the managed side.

**Comment by FiniteReality** [comment]
> Maybe, instead of returning the "closest" and taking a "filter" we could expose a function that takes a "predicate" that is called for each "device descriptor" that allows them to decide if it "fits" without actually instantiating something on the managed side.

How would we specify the property then? Something like LINQ expressions is what comes to mind:
```cs
ValueTask<IAudioAdapter> FindClosestAdapter<TType, TProperty>(Expression<Func<TType, TProperty>> propertySelector, Func<TProperty, bool> predicate)
```

However, that would mean TProperty would need to be specified too (until we get partial type influence) which seems kind of ugly...

Another option would be to return a struct to make it cleaner:
```cs
struct AdapterSearcher<T> where T : AudioAdapterFilter
{
    public ValueTask<IAudioAdapter> FindAsync<TProperty>(Expression<Func<T, TProperty>> propertySelector, Func<TProperty, bool> predicate);
}

//...
AdapterSearcher<T> CreateAdapterSearcher<TType>()
```

That way, we only need to specify TType and then the rest can be inferred.

**Comment by tannergooding** [comment]
I was just thinking something like:

```csharp
struct AudioAdapterInfo
{
    AudioDeviceType DeviceType { get; }
    string Name { get; }
    int SampleRate { get; }
    int BitDepth { get; }
    int Channels { get; }
    bool IsBigEndian { get; }
}

public IAudioAdapter GetAudioAdapter(Func<AudioAdapterInfo, bool> predicate);
// likely using a customized `Func` where `AudioAdapterInfo` is passed by `in`
```

This would then just enumerate the info for each adapter and call the predicate for each. It then only create an `IAudioAdapter` for when the predicate returns `true`.

**Comment by FiniteReality** [comment]
How do we handle cases where providers can provide more information? For example, PulseAudio's `pa_sink_info` struct contains a lot of information, including the audio encoding (e.g. PCM, MPEG, DTS, etc) which are likely not exposed in the same way across providers.

**Comment by tannergooding** [comment]
I believe you would have to return the backing handle and allow the user to manually query the additional info themselves; if it isn't something that can be consistently exposed.

**Comment by FiniteReality** [comment]
I did some thinking, and one possible solution I came up with was to (ab)use explicit implementation. For example:

```cs
public interface IAudioAdapter { }

public struct AudioAdapterInfo { }
public struct DummyAudioAdapterInfo { }

public interface IAudioProvider
{
    IAudioAdapter GetAudioAdapter(Func<AudioAdapterInfo, bool> predicate);
}

public class DummyAudioProvider : IAudioProvider
{
    IAudioAdapter IAudioProvider.GetAudioAdapter(Func<AudioAdapterInfo, bool> predicate) { throw null; }
    public IAudioAdapter GetAudioAdapter(Func<DummyAudioAdapterInfo, bool> predicate) { throw null; }
}

public class UserCode
{
    private IAudioProvider _provider = null;

    public void DoStuff()
    {
        _provider.GetAudioAdapter((x) => true); // x is AudioAdapterInfo
        ((DummyAudioProvider)_provider).GetAudioAdapter((x) => true); // x is DummyAudioAdapterInfo
    }
}
```

We may end up having to duplicate struct members, but this means that the 99% use case is still very easy, and only users who need to query for specific properties on their provider have to jump through a relatively minor hoop.

A possible solution to the struct problem would be to create an interface with the base members, and document it as being for provider implementors to ensure the required members are available.

**Comment by tannergooding** [comment]
I think that is a bit more complicated than probably necessary.

Ultimately, you are just wanting to enumerate adapters and find one that matches what you want. The "downside" to enumerating the concrete adapters is that you require an allocation per device to get that.

However, that allocation is not particularly bad, especially if its a one time cost and initialization is lazy.

Exposing an `AudioAdapterInfo` removes the allocation concern and allows users to check if something meets their needs; but that might also be overkill for common scenarios (especially if initialization is lazy).

**Comment by tannergooding** [comment]
I've marked making the properties `readonly` as approved.

I would like to discuss how we want to support filtering a bit more, however.

**Comment by tannergooding** [comment]
Issue was resolved with https://github.com/terrafx/terrafx/pull/47

The filtering API should likely be tracked by a separate issue.
