### ISSUE TITLE
[Question] Can't clone project, no access to https://tagoo@dev.azure.com/tagoo/terrafx/

### ISSUE THREAD

**Issue by HurricanKai** [terrafx/terrafx#52]
When trying to clone my Fork, I'm promted to login by LFS via the VS Credentials Window. But I do not have access to https://tagoo@dev.azure.com/tagoo/terrafx/
Looks like the pictures in /docs/samples/ still point to that repo? 
The specific error LFS returned is `Error downloading object: docs/samples/D3D12.EnumerateGraphicsAdapters - Windows.png (36b7ddb): Smudge error: Error downloading docs/samples/D3D12.EnumerateGraphicsAdapters - Windows.png (36b7ddb1857f88dc4185de8e563fe34cee8f284d1e714519b905c3ffe5a0ac23): batch response: Git credentials for https://tagoo@dev.azure.com/tagoo/terrafx/_git/terrafx.git/info/lfs not found.`
[Full Log](https://github.com/terrafx/terrafx/files/3754302/20191022T095126.3927827.log)

**Comment by HurricanKai** [comment]
Looking at the contents of those "pictures" these are only supposed to be pictures, but Github was equally confused when the repo was moved from there (?) and just wrote the LFS Info into those files, to not fail.

**Comment by HurricanKai** [comment]
Was able to resolve by deleting files in the /docs/sample from github directly and cloning that specific branch

**Comment by tannergooding** [comment]
> just wrote the LFS Info into those files, to not fail.

This is how Git LFS works. Binary files are actually stored as a little "stub" file that just contains some info for downloading it from Git LFS.

> When trying to clone my Fork, I'm promted to login by LFS via the VS Credentials Window.

This shouldn't be required; LFS should allow anonymous download and only require authentication for pushing artifacts up. The mirror repo is also listed as public: https://dev.azure.com/tagoo/terrafx

Hmmm....

**Comment by HurricanKai** [comment]
I see, very weird. Maybe it's due to me cloning using VS Checkout / the Github Extension (tried both of those) but looking at the logs it seems VS and that extension both just call down into git and set some Session Variables what executable to use for Authentication

**Comment by tannergooding** [comment]
> I see, very weird.

Yes, definitely. @FiniteReality tried (discussed on https://discord.terrafx.dev/) and everything appeared to work fine (both for direct and for cloning a fork). I also tried on a machine with no credential information.

**Comment by tannergooding** [comment]
I've had a couple other repors about this and it was breaking markdown rendering so I removed Git LFS in https://github.com/terrafx/terrafx/pull/69. I'm going to think some more about how to handle assets moving forward.
