### ISSUE TITLE
[PROPOSAL] Make IGraphicsContext and IWindow IDispoable

### ISSUE THREAD

**Issue by HurricanKai** [terrafx/terrafx#53]
#### Rationale
This would remove an extra nesting level required right from the beginning of the Project, and allow the usage of `using`, removing the need to manually insert a `try { } finally { }` which would be quite useful for experimenation, when there is little abstraction, and causing issues is common (therefore catching issues is important)

#### Proposed API
```diff
- public interface IWindow
+ public interface IWindow : IDisposable
{
+    void Dispose();
}

- public interface IGraphicsContext
+ public interface IGraphicsContext : IDisposable
{
+    void Dispose();
}
```
Note: `void Dispose()` is implicit
#### Drawbacks
- Future providers might need to implement an empty implementation of `IDisposable.Dispose`, but this is unlikely, as Graphics generally rely on unmanaged resources (all current do)
- Future providers cannot choose to use `IAsyncDisposable` instead of `IDisposable`, but this would've been a hazard to the current implementation anyways. therefore I don't consider this a drawback worth considering

#### Alternatives
The current solution is to check if the returned implementation of `IWindow` / `IGraphicsContext` implement `IDisposable` and Dispose them if needed, which also requires a manual `try { } finally { }` 
instead of a `using var ... = ...`

#### Other thoughts
I assume that this has been thought of, but there was some reasoning behind not doing this, but I cannot think of why, in part writing this because I'm curious of the reasoning

**Comment by FiniteReality** [comment]
IAsyncDisposable would probably be better, with providers documenting whether the operation is performed asynchronously or not.

**Comment by HurricanKai** [comment]
maybe, but all current implementations use `IDisposable` and I can't think of a case where it makes sense to use `IAsyncDisposable` when releasing these resources

**Comment by FiniteReality** [comment]
Another possibility would be to use StartAsync/StopAsync-style initialization/finalization, and have the IDisposable/IAsyncDisposable be an implementation decision instead. This would provide symmetry with the audio provider.

**Comment by tannergooding** [comment]
I'm fine with making these disposable by default, and I can avoid the need for users to implement an empty `Dispose` method by using default interface methods.

I don't think `IAsyncDisposable` is appropriate. Most of these types need to be disposed/managed from a central thread and it may not be safe to dispose asynchronously.

**Comment by tannergooding** [comment]
I resolved this in https://github.com/terrafx/terrafx/pull/63.
