### ISSUE TITLE
[IDEA] Get required Vulkan Extensions from Windowing

### ISSUE THREAD

**Issue by HurricanKai** [terrafx/terrafx#57]
I'm not sure how this could be done, but it would be nice if the Windowing Providers would provide a function that returns required Vulkan Extensions

**Comment by tannergooding** [comment]
@HurricanKai, in https://github.com/terrafx/terrafx/pull/62 I added several new constants:
* `TerraFX.Graphics.Providers.Vulkan.OptionalExtensionNamesDataName`
* `TerraFX.Graphics.Providers.Vulkan.OptionalLayerNamesDataName`
* `TerraFX.Graphics.Providers.Vulkan.RequiredExtensionNamesDataName`
* `TerraFX.Graphics.Providers.Vulkan.RequiredLayerNamesDataName`

These can be used with `AppContext.GetData(name)` to get a string of semicolon separate values representing the required or optional component names (as set by the user or other providers).

Does this solve your request?

I could likely also surface a `ReadOnlySpan<string>` for the names used by a particular instance if needed...

**Comment by HurricanKai** [comment]
I can't find where they are set using github, but if they are set & are set to UTF8 byte arrays, that is the perfect solution to my request!

**Comment by tannergooding** [comment]
They are set in the constructor for the respective provides. For example, the libX11 provider sets it here: https://github.com/terrafx/terrafx/blob/master/sources/Providers/UI/Xlib/XlibWindowProvider.cs#L34-L36

They are not UTF8 byte arrays. They are currently a standard `string` that is semicolon separated.

C# 9 is supposed to add UTF8 String Literals, at which point I will likely switch it over to that to avoid conversion overhead.

**Comment by HurricanKai** [comment]
:+1: thank you
