### ISSUE TITLE
Unable to find package TerraFX. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by MrCHB1** [terrafx/terrafx#88]
I tried using dotnet add package, but it says its not found. Why?

**Comment by tannergooding** [comment]
As from the readme:
> Packages are available at: https://github.com/orgs/terrafx/packages or via the NuGet Feed URL: https://pkgs.terrafx.dev/index.json

There are no packages available on nuget.org yet as the API is still being developed and a public preview has not been made as of yet.
